apiVersion: v1
kind: Secret
metadata:
  name: cronmail-secret
  namespace: cronmail
type: Opaque
stringData:
  MAIL_ENCRYPTION_KEY: "Af408K9-xM9yzcCcUHPpTC33TZjilWMmlkrqmjLjhZs="
  SMTP_HOST: ""
  SMTP_PORT: "465"
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""
  SMTP_SENDER_NAME: "CronMail"
  SMTP_SENDER_EMAIL: ""
